services:
  - type: web
    name: two47convobot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatbot_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
      - key: SUPABASE_URL
      - key: SUPABASE_SERVICE_ROLE_KEY
      - key: API_TOKEN
      - key: SUPABASE_TABLE_NAME_KB
        value: client_knowledge_base
      - key: SUPABASE_TABLE_NAME_LOG
        value: client_conversations

    # <-- here’s the change: publish your `static/` folder
    staticPublishPath: static
