services:
  - type: web
    name: two47convo-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatbot_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_TABLE_NAME
        value: client_knowledge_base
    staticPublishPath: ""  # Disables auto static hosting so FastAPI handles /configs
